#!/usr/bin/env python3
"""
AIM – AI Engineering Manifest Generator
Generates CLAUDE.md (and optionally .codex/init.md) from AIM.yaml.

Usage:
    python generate_aim.py                        # generates CLAUDE.md in cwd
    python generate_aim.py --phase kickoff        # only kickoff phase
    python generate_aim.py --format codex         # generate .codex/init.md
    python generate_aim.py --all                  # generate all output formats
    python generate_aim.py --list                 # list all phases and checks
"""

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML not found. Install it with: pip install pyyaml")
    sys.exit(1)


# ─── TEMPLATES ────────────────────────────────────────────────────────────────

CLAUDE_MD_HEADER = """\
<!--
  Auto-generated by generate_aim.py from AIM.yaml
  DO NOT EDIT MANUALLY – edit AIM.yaml instead.
  Regenerate: python generate_aim.py
-->

# {name}

> *{tagline}*

{description}

---

## ⚠️ AIM INIT — Read this first, before doing anything else

Follow this decision tree exactly:

### Step 1 — Check initialization state

Does `.claude/aim.initialized` exist?

- **NO** → Go to **Step 2** (full AIM run)
- **YES** → Go to **Step 3** (check for deferred items)

---

### Step 2 — Full AIM run (first start in this repo)

Work through the full checklist below, phase by phase.

For each check, the user can respond with:
- ✅ **Done** → confirmed, continue
- ❌ **Blocker** → do not proceed until resolved (blocking checks only)
- ⏳ **Later** → note it as deferred, continue

When all blocking checks are confirmed:
1. Collect all items marked ⏳ **Later**
2. Write them to `.claude/aim.deferred.md` in this format:
   ```
   # AIM – Deferred Items
   <!-- Auto-written by Claude Code. Edit or delete items as you resolve them. -->

   - [ ] [check_id] Title of the deferred check
   - [ ] [check_id] Another deferred check
   ```
3. Create `.claude/aim.initialized` with content: `AIM completed: <current datetime>`
4. Tell the user: "✅ AIM complete. [N deferred items logged to .claude/aim.deferred.md]"
5. Proceed with the user's actual task.

---

### Step 3 — Deferred items check (subsequent starts)

Does `.claude/aim.deferred.md` exist and contain unchecked items (`- [ ]`)?

- **NO** → Nothing pending. Proceed normally. 🚀
- **YES** → Show the user the open items:
  ```
  ⏳ AIM – Open items from last time:
  - [ ] [check_id] ...
  - [ ] [check_id] ...

  Resolve now, defer again, or mark as done?
  ```
  For each item, let the user respond:
  - ✅ **Done** → mark as `- [x]` in the file
  - ⏳ **Later** → leave as `- [ ]`, keep for next start
  - 🗑️ **Drop** → remove the line entirely

  After processing all items: proceed with the user's actual task.

---

### Reset

To re-run the full AIM checklist: `python generate_aim.py --reset`
This deletes `.claude/aim.initialized` and `.claude/aim.deferred.md`.

---

## AIM Checklist — only used in Step 2

Rules:
- **Blocking** (`🔒`) = must be confirmed, ⏳ Later is not allowed
- **Non-blocking** (`💡`) = can be deferred with ⏳ Later
- **Recurring** (`🔁`) = reminder for later in the hackathon, always deferrable

---
"""

CODEX_HEADER = """\
# {name} — Codex Init Checklist

> *{tagline}*

Generated from AIM.yaml. Run at project start.

---
"""

PHASE_TEMPLATE = """\
## {emoji} Phase {n}: {label}

{description}

"""

CHECK_TEMPLATE_CLAUDE = """\
### {blocking_icon} {title}
{description}

**Prompt for AI:**
> {prompt}

**Anti-pattern to avoid:** _{anti_pattern}_

---
"""

CHECK_TEMPLATE_CODEX = """\
- [{done}] **{title}** {blocking_tag}
  {description}
"""

PHASE_SEPARATOR = "\n---\n\n"


# ─── GENERATOR ────────────────────────────────────────────────────────────────

def load_aim(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def blocking_icon(blocking: bool, phase_blocking: bool = False) -> str:
    if blocking or phase_blocking:
        return "🔒"
    return "💡"


def is_recurring(check_id: str) -> bool:
    recurring_ids = {"challenge_realignment", "no_solo_tunneling", "pause_slots_protected"}
    return check_id in recurring_ids


def render_check_claude(check: dict, phase_blocking: bool) -> str:
    check_blocking = check.get("blocking", False)
    icon = blocking_icon(check_blocking, phase_blocking)
    if is_recurring(check.get("id", "")):
        icon = "🔁"

    description = check.get("description", "").strip().replace("\n", " ")
    prompt = check.get("prompt", "").strip().replace("\n", " ")
    anti_pattern = check.get("anti_pattern", "—").strip()

    return CHECK_TEMPLATE_CLAUDE.format(
        blocking_icon=icon,
        title=check["title"],
        description=description,
        prompt=prompt,
        anti_pattern=anti_pattern,
    )


def render_check_codex(check: dict, phase_blocking: bool) -> str:
    check_blocking = check.get("blocking", False)
    blocking_tag = "*(blocking)*" if (check_blocking or phase_blocking) else ""
    description = check.get("description", "").strip().replace("\n", " ")[:120]

    return CHECK_TEMPLATE_CODEX.format(
        done=" ",
        title=check["title"],
        blocking_tag=blocking_tag,
        description=description,
    )


def render_phase_claude(phase_key: str, phase: dict, n: int) -> str:
    label = phase.get("label", phase_key)
    emoji = phase.get("emoji", "")
    description = phase.get("description", "").strip()
    phase_blocking = phase.get("blocking", False)
    checks = phase.get("checks", [])

    output = PHASE_TEMPLATE.format(n=n, emoji=emoji, label=label, description=description)

    for check in checks:
        output += render_check_claude(check, phase_blocking)

    return output


def render_phase_codex(phase_key: str, phase: dict, n: int) -> str:
    label = phase.get("label", phase_key)
    emoji = phase.get("emoji", "")
    phase_blocking = phase.get("blocking", False)
    checks = phase.get("checks", [])

    output = f"\n### {emoji} {label}\n\n"
    for check in checks:
        output += render_check_codex(check, phase_blocking)

    return output


def render_ai_principles_claude(principles_block: dict) -> str:
    label = principles_block.get("label", "AI Principles")
    emoji = principles_block.get("emoji", "🤖")
    description = principles_block.get("description", "").strip()
    principles = principles_block.get("principles", [])

    output = f"## {emoji} {label}\n\n{description}\n\n"

    for p in principles:
        output += f"### {p['title']}\n"
        output += f"{p.get('description', '').strip()}\n\n"
        rule = p.get("rule", "")
        if rule:
            output += f"**Rule:** _{rule}_\n\n"
        output += "---\n\n"

    return output


def generate_claude_md(aim: dict, phase_filter: str | None = None) -> str:
    header = CLAUDE_MD_HEADER.format(
        name=aim.get("name", "AIM"),
        tagline=aim.get("tagline", ""),
        description=aim.get("description", "").strip(),
    )

    phases = aim.get("phases", {})
    body = ""
    for n, (key, phase) in enumerate(phases.items(), start=1):
        if phase_filter and key != phase_filter:
            continue
        body += render_phase_claude(key, phase, n)
        body += PHASE_SEPARATOR

    # AI Principles section
    if "ai_principles" in aim and not phase_filter:
        body += render_ai_principles_claude(aim["ai_principles"])

    return header + body


def generate_codex_md(aim: dict) -> str:
    header = CODEX_HEADER.format(
        name=aim.get("name", "AIM"),
        tagline=aim.get("tagline", ""),
    )

    phases = aim.get("phases", {})
    body = ""
    for n, (key, phase) in enumerate(phases.items(), start=1):
        body += render_phase_codex(key, phase, n)

    return header + body


def list_checks(aim: dict) -> None:
    phases = aim.get("phases", {})
    print(f"\n{aim.get('name', 'AIM')} – Check Overview\n{'─' * 50}")
    total = 0
    for key, phase in phases.items():
        checks = phase.get("checks", [])
        label = phase.get("label", key)
        emoji = phase.get("emoji", "")
        blocking = "🔒 BLOCKING" if phase.get("blocking") else ""
        print(f"\n{emoji} {label}  {blocking}")
        for check in checks:
            icon = "🔒" if check.get("blocking") else "💡"
            if is_recurring(check.get("id", "")):
                icon = "🔁"
            print(f"  {icon}  [{check['id']}] {check['title']}")
            total += 1
    print(f"\n{'─' * 50}")
    print(f"Total checks: {total}")


# ─── CLI ──────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="AIM – AI Engineering Manifest Generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--aim",
        default="AIM.yaml",
        help="Path to AIM.yaml (default: ./AIM.yaml)",
    )
    parser.add_argument(
        "--phase",
        default=None,
        help="Generate only a specific phase (e.g. --phase kickoff)",
    )
    parser.add_argument(
        "--format",
        choices=["claude", "codex", "all"],
        default="claude",
        help="Output format: claude (CLAUDE.md), codex (.codex/init.md), all (default: claude)",
    )
    parser.add_argument(
        "--out",
        default=None,
        help="Output file path (default: CLAUDE.md or .codex/init.md)",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List all phases and checks without generating files",
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Delete .claude/aim.initialized so AIM triggers again on next claude start",
    )
    return parser.parse_args()


def write_file(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"✅  Generated: {path}")


def ensure_gitignore(paths: list[Path]) -> None:
    """Add sentinel files to .gitignore if not already present."""
    gitignore = Path(".gitignore")
    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    added = []
    for p in paths:
        entry = str(p)
        if entry not in existing:
            existing = existing.rstrip() + f"\n{entry}\n"
            added.append(entry)
    if added:
        gitignore.write_text(existing, encoding="utf-8")
        for entry in added:
            print(f"📝  Added {entry} to .gitignore")


def main() -> None:
    args = parse_args()

    sentinel = Path(".claude/aim.initialized")
    deferred = Path(".claude/aim.deferred.md")

    if args.reset:
        deleted = []
        for f in [sentinel, deferred]:
            if f.exists():
                f.unlink()
                deleted.append(str(f))
        if deleted:
            for d in deleted:
                print(f"🔄  Reset: deleted {d}")
            print("    AIM will trigger on next `claude` start.")
        else:
            print(f"ℹ️   Nothing to reset – AIM would already trigger.")
        return

    aim_path = Path(args.aim)
    if not aim_path.exists():
        print(f"❌  AIM.yaml not found at: {aim_path}")
        sys.exit(1)

    aim = load_aim(aim_path)

    if args.list:
        list_checks(aim)
        return

    fmt = args.format

    if fmt in ("claude", "all"):
        content = generate_claude_md(aim, phase_filter=args.phase)
        out_path = Path(args.out) if args.out else Path("CLAUDE.md")
        write_file(out_path, content)

    if fmt in ("codex", "all"):
        content = generate_codex_md(aim)
        out_path = Path(args.out) if args.out and fmt == "codex" else Path(".codex/init.md")
        write_file(out_path, content)

    ensure_gitignore([sentinel, deferred])

    print("\nDone. Commit AIM.yaml, CLAUDE.md and .gitignore. 🚀")
    print(f"Tip: run `python generate_aim.py --reset` to re-trigger AIM on next start.")


if __name__ == "__main__":
    main()
